'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { summarizeCourseMaterials } from '@/ai/flows/summarize-course-materials';

import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Loader2, Wand2 } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { useToast } from '@/hooks/use-toast';

const formSchema = z.object({
  courseMaterials: z.string().min(50, {
    message: 'Course materials must be at least 50 characters.',
  }),
});

export function SummarizationTool() {
  const [summary, setSummary] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      courseMaterials: '',
    },
  });

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true);
    setSummary(null);
    try {
      const result = await summarizeCourseMaterials(values);
      setSummary(result.summary);
    } catch (e: any) {
      toast({
        variant: 'destructive',
        title: 'Error Generating Summary',
        description: e.message || 'An unexpected error occurred.',
      });
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="space-y-6">
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
          <FormField
            control={form.control}
            name="courseMaterials"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Course Materials</FormLabel>
                <FormControl>
                  <Textarea
                    placeholder="Paste your course documentation, course.yml content, or lecture notes here."
                    className="min-h-[200px] font-code text-sm"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <Button type="submit" disabled={isLoading}>
            {isLoading ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <Wand2 className="mr-2 h-4 w-4" />
            )}
            Summarize
          </Button>
        </form>
      </Form>

      {summary && (
        <Card className="mt-6">
          <CardHeader>
            <CardTitle>Generated Summary</CardTitle>
            <CardDescription>This summary was generated by AI to help with quality assurance.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="prose prose-sm dark:prose-invert max-w-none text-card-foreground/90">
              {summary}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
